[package]
name = "tracing-fmt-glog"
version = "0.1.0"
edition = "2021"

[features]
default = ["ansi"]
ansi = ["tracing-subscriber/ansi"]

[dependencies]
tracing-core = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3.2", features = ["std", "fmt", "registry"] }
chrono = { version = "0.4", features = ["clock", "serde", "std"], default-features = false }
ansi_term = "0.12"

[dev-dependencies]
thiserror = "1"